site_name: Finitewave
site_description: Documentation for the Finitewave package for modeling cardiac electrophysiology
repo_url: https://github.com/TiNezlobinsky/Finitewave

theme:
  name: material

nav:
  - Home: index.md
  - User Guide:
    - user-guide/index.md
    - Quick Start: user-guide/quick_start.md
    - Development: user-guide/development.md
    - Examples: user-guide/examples/generated
  - API Reference: reference/


theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy

plugins:
  - search
  - section-index # Set an index page for sections

  # Generate API reference
  - gen-files:
      scripts:
        - docs/api-reference/generate_api_reference.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          load_external_modules: true
          options:
            show_source: false
            show_root_toc_entry: false
            show_symbol_type_heading: true
            merge_init_into_class: true
            docstring_style: numpy
            show_if_no_docstring: true

  # Generate example gallery
  - gallery:
      examples_dirs: examples/
      gallery_dirs: docs/user-guide/examples/generated
      conf_script: docs/user-guide/examples/gallery_conf.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

